theme: jekyll-theme-slate
title: Dyingday's Streamer Bot
description: A bot designed specifically for Streamers. Provides a chat integration between your Discord and Twitch Channel. Moderates both Twitch and Discord! WIP!
